FROM python:3.10
RUN pip install --upgrade pip

WORKDIR /app

COPY app/requirements-gradio.txt .
RUN pip install --default-timeout=300 -r requirements-gradio.txt


COPY app/poster_gradio.py /app/poster_gradio.py


EXPOSE 7860

CMD ["python", "poster_gradio.py"]
