FROM python:3.10

WORKDIR /app

COPY app/requirements-api.txt .

RUN pip install --upgrade pip


RUN pip install torch torchvision \
    --index-url https://download.pytorch.org/whl/cpu


RUN pip install -r requirements-api.txt

COPY app /app
COPY models /app/models
COPY exp /app/exp
COPY indexes /app/indexes

EXPOSE 5075
CMD ["python", "poster_api.py"]
